# Generated FPGA Pipeline
stages:
  - synth
  - elab

synth_lsio_au_test_fpga:
  stage: synth
  tags: ["soc-fpga-synth"]
  script:
    - "echo synth TARGET='lsio_au'"
    - "echo 'Executing: make -f Makefile synth '"
    - "make -f Makefile synth "
  rules:
    - if: "$CI_MERGE_REQUEST_ID"

synth_lsio_au_2_test_fpga:
  stage: synth
  tags: ["soc-fpga-synth"]
  script:
    - "echo synth VAR='FPGA_BOARD_TYPE=VCU118 USE_ORIG_MEM=1' OPTIONS='--write-netlist --disable-reports' TARGET='lsio_au_2'"
    - "echo 'Executing: make -f Makefile synth FPGA_BOARD_TYPE=VCU118 USE_ORIG_MEM=1 --write-netlist --disable-reports'"
    - "make -f Makefile synth FPGA_BOARD_TYPE=VCU118 USE_ORIG_MEM=1 --write-netlist --disable-reports"
  rules:
    - if: "$CI_MERGE_REQUEST_ID"

elab_lsio_au_elab_test_fpga:
  stage: elab
  tags: ["soc-fpga-elab"]
  script:
    - "echo elab VAR='FPGA_BOARD_TYPE=HTG960' TARGET='lsio_au_elab'"
    - "echo 'Executing: make -f Makefile elab FPGA_BOARD_TYPE=HTG960'"
    - "make -f Makefile elab FPGA_BOARD_TYPE=HTG960"
  rules:
    - if: "$CI_MERGE_REQUEST_ID"

